"""add system_prompt to businesses

Revision ID: 4f8591b800e2
Revises: b10308a55a4d
Create Date: 2026-07-28 11:00:54.314652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8591b800e2'
down_revision: Union[str, Sequence[str], None] = 'b10308a55a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('system_prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'system_prompt')
    # ### end Alembic commands ###
